window.dict = {
  'zh-CN': {
    NAV_HOME: `主页`,
    NAV_WHYUS: `优势`,
    NAV_TEAM: `团队`,
    NAV_TOKEN_TERMS: `条款`,
    NAV_ROADMAP: `路线`,
    NAV_NEWS: `新闻`,
    CURRENT_LANGUAGE: `中文`,
    LOGIN: `登录`,
    REGISTER: `注册`,
    ACCOUNT: `用户中心`,
    WHITEPAPER: `白皮书`,

    SECTION_HOME_TITLE: `Influence Chain`,
    SECTION_HOME_SUBTITLE: `价值与影响力互联`,
    SECTION_HOME_DESC: `影链基于区块链的特性和优势，创建了一个基于Token的生态系统，以及服务于生态的价值交易平台，将影响力 (个性化的知识产权)转化为代币持有者的数字资产。`,

    SECTION_PROBLEM_TITLE: `市场痛点`,
    SECTION_PROBLEM_SUB_TITLE: `目前的粉丝经济市场`,
    SECTION_PROBLEM_DESC: `无论影响力价值得到公众认可的程度有多高，仍存在未解决的挑战，没有可行的行业解决方案。`,
    SECTION_PROBLEM_LIST_ITEM_1: `不可量化: Fanbase由平台集中化，迫切需要解决跨平台可操作性问题。`,
    SECTION_PROBLEM_LIST_ITEM_2: `无法货币化:无赞助或广告合同，未实现货币化。`,
    SECTION_PROBLEM_LIST_ITEM_3: `未标准化:缺乏行业标准或解决方案。`,

    SECTION_SOLUTION_TITLE: `我们的解决方案`,
    SECTION_SOLUTION_SUB_TITLE: `Influence chain期待创建一个基于代币的生态系统。`,
    SECTION_SOLUTION_LIST_ITEM_1: `代币化使无法量化变得可量化。`,
    SECTION_SOLUTION_LIST_ITEM_2: `影响力交易平台将无形资产转化为数字资产。`,
    SECTION_SOLUTION_LIST_ITEM_3: `影响力指数用以评估影响力人物对各个方面的影响力。`,

    SECTION_INFLUENCER_TITLE: `影响力人物`,
    SECTION_INFLUENCER_ITEM_1: `流行偶像`,
    SECTION_INFLUENCER_ITEM_2: `体育英雄`,
    SECTION_INFLUENCER_ITEM_3: `企业家`,
    SECTION_INFLUENCER_ITEM_4: `电影明星`,
    SECTION_INFLUENCER_ITEM_5: `博主`,
    SECTION_INFLUENCER_ITEM_6: `意见领袖`,

    SECTION_INEX_TITLE: `影响力交易平台（INEX）`,
    SECTION_INEX_SUB_TITLE: `影响力交易平台(INEX)是整个区块链应用在Influence chain中的核心价值。通过该平台，潜在的影响力可以通过使用代币来流通和变现。`,

    SECTION_BUYCLUB_TITLE: `基于代币的应用 - BuyClub`,
    SECTION_BUYCLUB_SUB_TITLE: `BuyClub 是首个使用区块链帮助足球俱乐部等级股权和筹集资金的平台。它是 Influence chain 生态系统的重要应用之一。`,

    SECTION_INNOVATION_TITLE: `创新`,
    SECTION_INNOVATION_SUB_TITLE_1: `对于影响力人物`,
    SECTION_INNOVATION_SUB_TITLE_2: `对于支持者/粉丝`,
    SECTION_INNOVATION_ITEM_1: `Influence chain为影响力人物提供了一种创新型途径，通过科学地分解动态变化来量化其影响力。`,
    SECTION_INNOVATION_ITEM_2: `Influence chain为影响力人物提供了一种创新方式来获得粉丝的支持，并与他们的粉丝互动。`,
    SECTION_INNOVATION_ITEM_3: `对于影响力人物和粉丝来说，双向流动可以从INC 代币中获得价值，而非粉丝单向投入，没有任何可量化回报。`,
    SECTION_INNOVATION_ITEM_4: `支持者/粉丝和影响力人物之间日常互动更加亲密，借以对影响力交易平台定价，以及为代币效用开发应用程序。`,

    SECTION_TEAM_TITLE: `团队`,
    SECTION_TEAM_MEMBER_NAME_01: `宦晶羽`,
    SECTION_TEAM_MEMBER_TITLE_01: `创始人`,
    SECTION_TEAM_MEMBER_NAME_02: `葛 瑶`,
    SECTION_TEAM_MEMBER_TITLE_02: `合伙运营联合创始人`,
    SECTION_TEAM_MEMBER_NAME_03: `夏 亨`,
    SECTION_TEAM_MEMBER_TITLE_03: `联合创始人 | 亚太运营中心合伙人`,
    SECTION_TEAM_MEMBER_NAME_04: `Freed Ma`,
    SECTION_TEAM_MEMBER_TITLE_04: `合伙人 | 亚太运营中心首席运营官`,
    SECTION_TEAM_MEMBER_NAME_05: `李晓君`,
    SECTION_TEAM_MEMBER_TITLE_05: `合伙人 | 亚太运营中心首席执行官`,
    SECTION_TEAM_MEMBER_NAME_06: `谢歆尧`,
    SECTION_TEAM_MEMBER_TITLE_06: `联合创始人 | Sports Influence 主管`,
    SECTION_TEAM_MEMBER_NAME_07: `Shayda Osman Jalal`,
    SECTION_TEAM_MEMBER_TITLE_07: `欧洲和中东运营中心合作人`,
    SECTION_TEAM_MEMBER_NAME_08: `Park Cheol Min`,
    SECTION_TEAM_MEMBER_TITLE_08: `韩国运营团队合伙人`,
    SECTION_TEAM_MEMBER_NAME_09: `Kim Si Eun`,
    SECTION_TEAM_MEMBER_TITLE_09: `韩国运营团队合伙人`,
    SECTION_TEAM_MEMBER_NAME_10: `James Wong`,
    SECTION_TEAM_MEMBER_TITLE_10: `全球业务开发联合创始人`,
    SECTION_TEAM_MEMBER_NAME_11: `麻 跃`,
    SECTION_TEAM_MEMBER_TITLE_11: `业务开发总监`,
    SECTION_TEAM_MEMBER_NAME_12: `李渊敏`,
    SECTION_TEAM_MEMBER_TITLE_12: `营销总监`,
    SECTION_TEAM_MEMBER_NAME_13: `刘祁楠`,
    SECTION_TEAM_MEMBER_TITLE_13: `影响力人物运营总监`,
    SECTION_TEAM_MEMBER_NAME_14: `张路遥`,
    SECTION_TEAM_MEMBER_TITLE_14: `产品总监`,
    SECTION_TEAM_MEMBER_NAME_15: `吕 纲`,
    SECTION_TEAM_MEMBER_TITLE_15: `技术总监`,
    SECTION_TEAM_MEMBER_NAME_16: `李欣雨`,
    SECTION_TEAM_MEMBER_TITLE_16: `社区运营总监`,

    SECTION_PARTNER_TITLE: `合作伙伴`,
    SECTION_PARTNER_INTRO_1: `Anomaly是一家于2004年在纽约成立的广告代理商。该代理商在洛杉矶、纽约、多伦多、伦敦、阿姆斯特丹和上海设有办事处。`,
    SECTION_PARTNER_INTRO_2: `Gingkoo（代码：837901）成立于2013年，这使我们成为了中国最年轻的新三板(NEEQ)上市公司。`,
    SECTION_PARTNER_INTRO_3: `全球区块链研究中心，简称GBC，是一家专门从事区块链研究的独立研究机构，致力于区块链行业的发展。`,
    SECTION_PARTNER_INTRO_4: `Alphacat 将是世界上第一个基于数字货币的量化投资平台，也是世界上第一个机器人市场，为各种目的的人工智能和大数据提供交易和投资管理。`,

    SECTION_DOCUMENT_TITLE: `文档`,
    SECTION_DOCUMENT_DOWNLOAD: `白皮书下载`,

    SECTION_INC_TOKEN_TITLE: `INC 代币`,
    SECTION_INC_TOKEN_SUB_TITLE: `代币销售计划`,
    SECTION_INC_TOKEN_STEP_1: `天使轮内部认购`,
    SECTION_INC_TOKEN_STEP_2: `第二轮内部认购`,
    SECTION_INC_TOKEN_STEP_3: `第一轮预售`,
    SECTION_INC_TOKEN_FINISHED: `完成销售`,

    SECTION_ROADMAP_TITLE: `路线图`,
    SECTION_ROADMAP_STEP_TITLE_1: `韩国首尔，Influence Chain发布会`,
    SECTION_ROADMAP_STEP_DESC_1: `Influence Chain首次在韩国发布，创建了第一个全球影响力价值指数。`,
    SECTION_ROADMAP_STEP_TITLE_2: `泰国曼谷Influence Chain发布会`,
    SECTION_ROADMAP_STEP_DESC_2: `Influence Chain在曼谷与泰国王室联合举办了一次发布会。`,
    SECTION_ROADMAP_STEP_TITLE_3: `迪拜Influence Chain发布会 & 影响力交易平台发布会`,
    SECTION_ROADMAP_STEP_DESC_3: `迪拜Influence Chain仪式成功结束，明星们一起推荐了Influence Chain的“体育影响力”。`,
    SECTION_ROADMAP_STEP_TITLE_4: `待续`,

    SECTION_NEWS_TITLE: `最新新闻`,
    SECTION_NEWS_ITEM_TITLE_1: `迪拜 Influence Chain 发布会 & 影响力交易平台发布会`,
    SECTION_NEWS_ITEM_TITLE_2: `邓加和许多足球巨星齐聚迪拜，为 Influence Chain 欧洲发布会助力！`,
    SECTION_NEWS_ITEM_TITLE_3: `Influence Chain 在曼谷与泰国王室联合举办了一次发布会`,
    SECTION_NEWS_ITEM_TITLE_4: `泰国王室成员、电影明星和来自世界各地的投资者都参加了在曼谷索菲特酒店举办的 Influence Chain 盛宴。`,
    SECTION_NEWS_ITEM_TITLE_5: `韩国首尔 Influence Chain 发布会`,

    SECTION_FOLLOW_TITLE_1: `重要事项跟进`,
    SECTION_FOLLOW_TITLE_2: `Influence Chain更新资讯`,

    FOOTER_POLICY: `代币销售协议`,
    FOOTER_TERMS: `隐私政策`,
    FOOTER_AGGREMENT: `条款`,
    FOOTER_FUNDATION: `Influence Chain 基金会`,

    IMG_PROBLEM: './home-assets/img/problem-cn.png',
    IMG_SOLUTION: './home-assets/img/solution-cn.png',
    IMG_INC_TOKEN_1: './home-assets/img/inc-token-1-cn.png',
    IMG_INC_TOKEN_2: './home-assets/img/inc-token-2-cn.png',

    DIALOG_LOGIN_TITLE: '登录',
    DIALOG_LOGIN_EMAIL: '邮箱',
    DIALOG_LOGIN_PASSWORD: '密码',
    DIALOG_LOGIN_IMAGE_CAPTCHA: '图形验证码',
    DIALOG_LOGIN_BTN_LOGIN: '登录',
    DIALOG_LOGIN_REMEMBER: '记住我',
    DIALOG_LOGIN_FORGET: '忘记密码？',

    DIALOG_REGISTER_TITLE: '注册',
    DIALOG_REGISTER_EMAIL: '邮箱',
    DIALOG_REGISTER_PASSWORD: '密码',
    DIALOG_REGISTER_IMAGE_CAPTCHA: '图形验证码',
    DIALOG_REGISTER_EMAIL_CAPTCHA: '邮箱验证码',
    DIALOG_REGISTER_BTN_REGISTER: '注册',
    DIALOG_REGISTER_CAN_NOT_REGISTER: '无法注册？',
    DIALOG_REGISTER_REGISTER_HELPER_1: '将您的邮箱、姓名、身份证号、身份证照片发送到',
    DIALOG_REGISTER_REGISTER_HELPER_2: '。我们将在 2 个工作日内完成验证，并将您的登录信息发送到您的邮箱',

    DIALOG_FORGET_TITLE: '重置密码',
    DIALOG_FORGET_EMAIL: '邮箱',
    DIALOG_FORGET_IMAGE_CAPTCHA: '图形验证码',
    DIALOG_FORGET_EMAIL_CAPTCHA: '邮箱验证码',
    DIALOG_FORGET_PASSWORD: '密码',
    DIALOG_FORGET_BTN_RESET: '重置',
    DIALOG_FORGET_BACK_TO_LOGIN: '返回登录',

    DIALOG_AUTHENTICATION_TITLE: '身份认证',
    DIALOG_AUTHENTICATION_SUB_TITLE: '提交申购钱请先进行身份认证',
    DIALOG_AUTHENTICATION_REALNAME: '真实姓名',
    DIALOG_AUTHENTICATION_ID_NUMBER: '证件号',
    DIALOG_AUTHENTICATION_UPLOAD: '请上传证件照片',
    DIALOG_AUTHENTICATION_UPLOAD_HINT: '请上传您的身份证或者护照的图片',
    DIALOG_AUTHENTICATION_IMAGE_CAPTCHA: '图形验证码',
    DIALOG_AUTHENTICATION_BTN_DONW: '完成',

    GET_CODE: '获取验证码',
    BTN_PRESALE: '预售',
    BTN_ACCOUNT: '账户',
    SELECT_NATIONALITY_DEFAULT: '- 选择国家 -',

    ERROR_INVALID_EMAIL: '请正确填写的邮箱地址',
    ERROR_INVALID_PASSWORD: '请正确填写密码',
    ERROR_INVALID_CAPTCHA: '请正确填写验证码',
    ERROR_INVALID_IMAGE_CAPTCHA: '请正确填写图形验证码',
    ERROR_INVALID_EMAIL_CAPTCHA: '请正确填写邮箱验证码',
    ERROR_EMPTY_REALNAME: '请输入真实姓名',
    ERROR_EMPTY_ID_NUMBER: '请输入证件号',
    ERROR_EMPTY_COUNTRY: '请输入国家',
    ERROR_EMPTY_ID_PHOTO: '请上传证件照片',

    MESSAGE_EMAIL_SENT: '邮件已发送',
    MESSAGE_PASSWORD_RESET: '密码已重置，现在带您去登录'
  },
  'en-US': {
    NAV_HOME: `HOME`,
    NAV_WHYUS: `WHY US`,
    NAV_TEAM: `TEAM`,
    NAV_TOKEN_TERMS: `TOKEN TERMS`,
    NAV_ROADMAP: `ROADMAP`,
    NAV_NEWS: `NEWS`,
    CURRENT_LANGUAGE: `English`,
    LOGIN: `LOGIN`,
    REGISTER: `REGISTER`,
    ACCOUNT: `ACCOUNT`,
    WHITEPAPER: `WHITEPAPER`,

    SECTION_HOME_TITLE: `Influence Chain`,
    SECTION_HOME_SUBTITLE: `Linking Influence and Value`,
    SECTION_HOME_DESC: `Influence chain creates a token based ecosystem that exploits the advantages of private blockchain by building up a token exchange where influential power (individualized intellectual property) can be monetized into digital assets for the token holders.`,

    SECTION_PROBLEM_TITLE: `PROBLEM OF INFLUENCE MARKET`,
    SECTION_PROBLEM_SUB_TITLE: `Fans Marketing Today`,
    SECTION_PROBLEM_DESC: `No matter how the value of influential power has been recognized by the public, there are still unsolved challenges with no applicable industrial solution.`,
    SECTION_PROBLEM_LIST_ITEM_1: `Unquantifiable: Fanbase is centralized by platforms, cross-platform operability is a pressing need`,
    SECTION_PROBLEM_LIST_ITEM_2: `Unmonetizable: No monetization without sponsorship or advert contracts`,
    SECTION_PROBLEM_LIST_ITEM_3: `No standardization: Lack of industrial standard or solution`,

    SECTION_SOLUTION_TITLE: `OUR SOLUTION`,
    SECTION_SOLUTION_SUB_TITLE: `Influence chain aspires to create a token based ecosystem whereby`,
    SECTION_SOLUTION_LIST_ITEM_1: `Tokenization turns unquantifiable into quantifiable.`,
    SECTION_SOLUTION_LIST_ITEM_2: `Influence Exchange to monetize intangible asset into digital asset.`,
    SECTION_SOLUTION_LIST_ITEM_3: `Influence Index to evaluate influential powers for every possible aspect of Influencer.`,

    SECTION_INFLUENCER_TITLE: `INFLUENCERS`,
    SECTION_INFLUENCER_ITEM_1: `Pop Icons`,
    SECTION_INFLUENCER_ITEM_2: `Sports Heros`,
    SECTION_INFLUENCER_ITEM_3: `Enterpreneurs`,
    SECTION_INFLUENCER_ITEM_4: `Movie Stars`,
    SECTION_INFLUENCER_ITEM_5: `Bloggers`,
    SECTION_INFLUENCER_ITEM_6: `Opinion Leaders`,

    SECTION_INEX_TITLE: `INFLUENCE EXCHANGE (INEX)`,
    SECTION_INEX_SUB_TITLE: `Influence Exchange (INEX) is the core value of entire blockchain applications under Influence chain’s umbrella. it is where the potential of influence can be liquidized and monetized through the use of tokens.`,

    SECTION_BUYCLUB_TITLE: `TOKEN BASED APPLICATIONS-BUYCLUB`,
    SECTION_BUYCLUB_SUB_TITLE: `BUYCLUB is the first platform which use blockchain to help football clubs to register their equities and raise funds. It's one of the important applications in the influence chain ecosystem.`,

    SECTION_INNOVATION_TITLE: `INNOVATIONS`,
    SECTION_INNOVATION_SUB_TITLE_1: `For influencers`,
    SECTION_INNOVATION_SUB_TITLE_2: `For supporters/fans`,
    SECTION_INNOVATION_ITEM_1: `Influence chain creates an innovative way for influencers to quantify their influential power by scientifically factoring in dynamic variations.`,
    SECTION_INNOVATION_ITEM_2: `Influence chain creates an innovative way for influencers to get support from their fans and interact with their fans.`,
    SECTION_INNOVATION_ITEM_3: `A two-way traffic for both influencers and fans to gain values from INC token, instead of one-way traffic for fans to invest without any quantifiable return.`,
    SECTION_INNOVATION_ITEM_4: `More interactive intimacy between supporters/fans and influencers on daily basis, whereby the pricing on Influence exchange, and applications developed for tokens’ utility.`,

    SECTION_TEAM_TITLE: `THE TEAM`,
    SECTION_TEAM_MEMBER_NAME_01: `Rain Huan`,
    SECTION_TEAM_MEMBER_TITLE_01: `Founder of Influence Chain`,
    SECTION_TEAM_MEMBER_NAME_02: `Yao Ge`,
    SECTION_TEAM_MEMBER_TITLE_02: `Co-Founder of Influence Chain Partnership Operation`,
    SECTION_TEAM_MEMBER_NAME_03: `Heng Xia`,
    SECTION_TEAM_MEMBER_TITLE_03: `Co-Founder of Influence Chain | Partner of Operation Center Asia-Pacific`,
    SECTION_TEAM_MEMBER_NAME_04: `Freed Ma`,
    SECTION_TEAM_MEMBER_TITLE_04: `Partner | COO of Operation Center Asia-Pacific`,
    SECTION_TEAM_MEMBER_NAME_05: `Jimmy Li`,
    SECTION_TEAM_MEMBER_TITLE_05: `Partner | CEO of Operation Center Asia-Pacific`,
    SECTION_TEAM_MEMBER_NAME_06: `Xinyao Xie`,
    SECTION_TEAM_MEMBER_TITLE_06: `Co-Founder of Influence Chain | Head of Sports Influence`,
    SECTION_TEAM_MEMBER_NAME_07: `Shayda Osman Jalal`,
    SECTION_TEAM_MEMBER_TITLE_07: `Partner of Operation Center Europe and Middle-East`,
    SECTION_TEAM_MEMBER_NAME_08: `Park Cheol Min`,
    SECTION_TEAM_MEMBER_TITLE_08: `Partner of Operation Team South Korea`,
    SECTION_TEAM_MEMBER_NAME_09: `Kim Si Eun`,
    SECTION_TEAM_MEMBER_TITLE_09: `Partner of Operation Team South Korea`,
    SECTION_TEAM_MEMBER_NAME_10: `James Wong`,
    SECTION_TEAM_MEMBER_TITLE_10: `Co-Founder of Influence Chain Global Business Development`,
    SECTION_TEAM_MEMBER_NAME_11: `Jackie Ma`,
    SECTION_TEAM_MEMBER_TITLE_11: `Business Development Director`,
    SECTION_TEAM_MEMBER_NAME_12: `Sophia Li`,
    SECTION_TEAM_MEMBER_TITLE_12: `Marketing Director`,
    SECTION_TEAM_MEMBER_NAME_13: `Jesse Liu`,
    SECTION_TEAM_MEMBER_TITLE_13: `Influencer Operating Director`,
    SECTION_TEAM_MEMBER_NAME_14: `Luyao Zhang`,
    SECTION_TEAM_MEMBER_TITLE_14: `Product Director`,
    SECTION_TEAM_MEMBER_NAME_15: `Gang Lv`,
    SECTION_TEAM_MEMBER_TITLE_15: `Technical Director of Influence Chain`,
    SECTION_TEAM_MEMBER_NAME_16: `Xinyu Li`,
    SECTION_TEAM_MEMBER_TITLE_16: `Community Operating  Director`,

    SECTION_PARTNER_TITLE: `PARTNERS`,
    SECTION_PARTNER_INTRO_1: `Anomaly is an advertising agency founded in 2004 in New York City. The agency has offices in Los Angeles, New York, Toronto, London, Amsterdam, and Shanghai.`,
    SECTION_PARTNER_INTRO_2: `Gingkoo (code: 837901) was founded in 2013, which makes us the youngest listed company of NEEQ (National Equities Exchange and Quotations) in china.`,
    SECTION_PARTNER_INTRO_3: `Global Blockchain Research Center, or GBC for short, is an independent research institute specializing in the research of blockchain and devoted to the development of blockchain industry.`,
    SECTION_PARTNER_INTRO_4: `Alphacat will be the world's first digital money-based quantitative investment platform and the world's first robot marketplace to offer trading and investment management of AI and big data for a variety of purposes.`,

    SECTION_DOCUMENT_TITLE: `DOCUMENTATION`,
    SECTION_DOCUMENT_DOWNLOAD: `DOWNLOAD WHITEPAPER`,

    SECTION_INC_TOKEN_TITLE: `INC TOKEN`,
    SECTION_INC_TOKEN_SUB_TITLE: `TOKEN SALE SCHEDULE`,
    SECTION_INC_TOKEN_STEP_1: `Angel Round Private Sale`,
    SECTION_INC_TOKEN_STEP_2: `Second Round Private Sale`,
    SECTION_INC_TOKEN_STEP_3: `First Round Pre-Sale`,
    SECTION_INC_TOKEN_FINISHED: `FINISHED`,

    SECTION_ROADMAP_TITLE: `ROADMAP`,
    SECTION_ROADMAP_STEP_TITLE_1: `Release conference of Influence Chain, Seoul, South Korea.`,
    SECTION_ROADMAP_STEP_DESC_1: `Influence Chain was released for the first time in South Korea, creating the first global influence value index.`,
    SECTION_ROADMAP_STEP_TITLE_2: `Release Conference of Influence Chain, Bangkok, Thailand.`,
    SECTION_ROADMAP_STEP_DESC_2: `Influence Chain held a release conference in Bangkok together with Thai royal families.`,
    SECTION_ROADMAP_STEP_TITLE_3: `Release Conference of Influence Chain, Dubai & The release conference of Influence Exchange.`,
    SECTION_ROADMAP_STEP_DESC_3: `The ceremony of Influence Chain, Dubai came to an end successfully, the stars recommended the "Sports Influence" of Influence Chain together！`,
    SECTION_ROADMAP_STEP_TITLE_4: `To be continue`,

    SECTION_NEWS_TITLE: `RECENT NEWS`,
    SECTION_NEWS_ITEM_TITLE_1: `Release Conference of Influence Chain, Dubai & The release conference of Influence Exchange`,
    SECTION_NEWS_ITEM_TITLE_2: `Dunga and many football superstars gathered in Dubai, cheering for the Release Conference of Influence Chain, Europe!`,
    SECTION_NEWS_ITEM_TITLE_3: `Influence Chain held a release conference in Bangkok together with Thai royal families`,
    SECTION_NEWS_ITEM_TITLE_4: `Thai royal family members,movie stars and investors from all over the world joined the feast of Influence Chain at Sofitel Bangkok`,
    SECTION_NEWS_ITEM_TITLE_5: `Release conference of Influence Chain, Seoul, South Korea.`,

    SECTION_FOLLOW_TITLE_1: `FOLLOW UP FOR IMPORTANT`,
    SECTION_FOLLOW_TITLE_2: `INFLUENCE CHAIN UPDATES`,

    FOOTER_POLICY: `Privacy Policy`,
    FOOTER_TERMS: `Terms`,
    FOOTER_AGGREMENT: `Token Sale Agreement`,
    FOOTER_FUNDATION: `Influence Chain Foundation`,

    IMG_PROBLEM: './home-assets/img/problem-en.png',
    IMG_SOLUTION: './home-assets/img/solution-en.png',
    IMG_INC_TOKEN_1: './home-assets/img/inc-token-1-en.svg',
    IMG_INC_TOKEN_2: './home-assets/img/inc-token-2-en.svg',

    DIALOG_LOGIN_TITLE: 'Login',
    DIALOG_LOGIN_EMAIL: 'Email',
    DIALOG_LOGIN_PASSWORD: 'Password',
    DIALOG_LOGIN_IMAGE_CAPTCHA: 'Image CAPTCHA',
    DIALOG_LOGIN_BTN_LOGIN: 'LOGIN',
    DIALOG_LOGIN_REMEMBER: 'Remember Me',
    DIALOG_LOGIN_FORGET: 'Forget ?',

    DIALOG_REGISTER_TITLE: 'Register',
    DIALOG_REGISTER_EMAIL: 'Email',
    DIALOG_REGISTER_PASSWORD: 'Password',
    DIALOG_REGISTER_IMAGE_CAPTCHA: 'Image CAPTCHA',
    DIALOG_REGISTER_EMAIL_CAPTCHA: 'Email CAPTCHA',
    DIALOG_REGISTER_BTN_REGISTER: 'REGISTER',
    DIALOG_REGISTER_CAN_NOT_REGISTER: 'Can not register ?',
    DIALOG_REGISTER_REGISTER_HELPER_1: 'Send your email, name, ID number, ID photos to',
    DIALOG_REGISTER_REGISTER_HELPER_2: '. Verification will be done in 2 work days. And your login info will be sent to your email.',

    DIALOG_FORGET_TITLE: 'Reset',
    DIALOG_FORGET_EMAIL: 'Email',
    DIALOG_FORGET_IMAGE_CAPTCHA: 'Image CAPTCHA',
    DIALOG_FORGET_EMAIL_CAPTCHA: 'Email CAPTCHA',
    DIALOG_FORGET_PASSWORD: 'Password',
    DIALOG_FORGET_BTN_RESET: 'RESET',
    DIALOG_FORGET_BACK_TO_LOGIN: 'Back to Login',

    DIALOG_AUTHENTICATION_TITLE: 'Authentication',
    DIALOG_AUTHENTICATION_SUB_TITLE: 'ID Authentication required for subscription',
    DIALOG_AUTHENTICATION_REALNAME: 'Real Name',
    DIALOG_AUTHENTICATION_ID_NUMBER: 'ID Number',
    DIALOG_AUTHENTICATION_UPLOAD: 'Upload ID Card Photo',
    DIALOG_AUTHENTICATION_UPLOAD_HINT: 'Please upload photo of your ID card / passport',
    DIALOG_AUTHENTICATION_IMAGE_CAPTCHA: 'Image CAPTCHA',
    DIALOG_AUTHENTICATION_BTN_DONW: 'DONE',

    GET_CODE: 'Get Code',
    BTN_PRESALE: 'PRE-SALE',
    BTN_ACCOUNT: 'ACCOUNT',
    SELECT_NATIONALITY_DEFAULT: '- Select Nationnality -',

    ERROR_INVALID_EMAIL: 'Invalid Email',
    ERROR_INVALID_PASSWORD: 'Invalid Password',
    ERROR_INVALID_CAPTCHA: 'Invalid CAPTCHA',
    ERROR_INVALID_IMAGE_CAPTCHA: 'Invalid Image CAPTCHA',
    ERROR_INVALID_EMAIL_CAPTCHA: 'Invalid Email CAPTCHA',
    ERROR_EMPTY_REALNAME: 'Please Enter Real Name',
    ERROR_EMPTY_ID_NUMBER: 'Please Enter ID Number',
    ERROR_EMPTY_COUNTRY: 'Please Select Country',
    ERROR_EMPTY_ID_PHOTO: 'Please Upload ID Photo',

    MESSAGE_EMAIL_SENT: 'Email Sent',
    MESSAGE_PASSWORD_RESET: 'Password Reset. Taking you to login.'
  }
}
